spring.application.name=FamilyHelpUae

spring.datasource.url=jdbc:mysql://localhost:3306/familyhelp
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
